version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  installation:
    docker:
      - image: cimg/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install Dependencies
          command: npm i
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules
      - run:
          name: run tests
          command: npm run test
  # Coverage:
  #   docker:
  #     - image: circleci/node:14.5.0
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run:
  #         name: Run tests and generate coverage report
  #         command: npm test -- --coverage --watchAll=false
  #     - codecov/upload:
  #         file: './coverage/clover.xml'
  #         token: ${CODECOV_TOKEN}workflows:
  push:
    jobs:
      - installation
      - coverage:
          requires: installation
